package dev.abelab.rippy.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class EventAnswerDate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_answer_date.answer_id
     *
     * @mbg.generated
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_answer_date.date_id
     *
     * @mbg.generated
     */
    private Integer dateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_answer_date.is_possible
     *
     * @mbg.generated
     */
    private Boolean isPossible;
}