package dev.abelab.rippy.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class EventTagging {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_tagging.event_id
     *
     * @mbg.generated
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_tagging.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;
}