package dev.abelab.rippy.db.mapper.base;

import dev.abelab.rippy.db.entity.EventDate;
import dev.abelab.rippy.db.entity.EventDateExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EventDateBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    long countByExample(EventDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int deleteByExample(EventDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int insert(EventDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int insertSelective(EventDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    List<EventDate> selectByExample(EventDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    EventDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EventDate record, @Param("example") EventDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EventDate record, @Param("example") EventDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EventDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_date
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventDate record);
}