package dev.abelab.rippy.db.mapper.base;

import dev.abelab.rippy.db.entity.EventTagging;
import dev.abelab.rippy.db.entity.EventTaggingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EventTaggingBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    long countByExample(EventTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    int deleteByExample(EventTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    int insert(EventTagging record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    int insertSelective(EventTagging record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    List<EventTagging> selectByExample(EventTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EventTagging record, @Param("example") EventTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tagging
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EventTagging record, @Param("example") EventTaggingExample example);
}