spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rippy?useSSL=false&allowPublicKeyRetrieval=true
    username: rippy
    password: rippy
    driver: com.mysql.cj.jdbc.Driver

slack:
  enabled: false
  webhook-url:

logging:
  level:
    root: ERROR
