name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Run back-end test
        env:
          TZ: "Asia/Tokyo"
        run: |
          docker-compose up -d
          ./gradlew -Dspring.profiles.active=test flywayMigrate
          ./gradlew -Dspring.profiles.active=test test
